### ISSUE TITLE
本文以外に必要な部分

### ISSUE THREAD

**Issue by znuko** [vuccaken/kaishi2019#16]
会誌を作成するにあたって、各員が担当するメインの内容部分以外に必要なパーツ。
1. （表）表紙
2. 中表紙
3. 巻頭言
4. 目次
5. 編集後記
6. 奥付
7. 裏表紙

**Comment by znuko** [comment]
目次は `00main.tex` に直接書くとして、他のパーツはそれぞれ別のtexファイルを用意する（？）

**Comment by znuko** [comment]
骨格は用意しました。あとは内容だけです。

**Comment by znuko** [comment]
表紙は多分nsmr君が描きます。多分。

**Comment by vckn** [comment]
hey

**Comment by znuko** [comment]
- 巻頭言：sj
- 編集後記：nkym
- 表紙：fjwr

でお願いします締切締切締切

**Comment by znuko** [comment]
完成！！！
