### ISSUE TITLE
`\bfseries` とかが効かない

### ISSUE THREAD

**Issue by vckn** [vuccaken/kaishi2019#38]
nkymのmacではちゃんと効く。

部室のpcだと効かない。

みんなの環境ではちゃんと和文の太字できてるのか？？？

**Comment by vckn** [comment]
フォントはもうむり。ヒラギノ搭載してないOSはだめだな

**Comment by znuko** [comment]
源ノのフォントを部室のノートpcの方にインスコしました。
丸ゴシックは無いですが、他はちゃんと出せます。

本番の会誌印刷は、源ノかヒラギノ（mac）どちらでやりましょうか

**Comment by znuko** [comment]
issueたてなおします
